
services:
  
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: db_associates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vini123
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  api:
    build: ./Backend
    volumes:
      - ./Backend:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/db_associates
    depends_on:
      - database
  
  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/code
    ports:
      - "5050:5050"
    depends_on:
      - api
  
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZTUyOTM2YzRhMGY2MTA3NGUyNjZhZmExYmQyOWE1MDYiLCJ0IjoiMDg2NWM4NTYtMmViOS00MmZkLTg0ZTYtMWYzZWEwMmJlYTAxIiwicyI6Ik4ySmxOREF6TUdZdFlqTXhaQzAwTTJOaExUZzBNbUl0Tm1ZeU5XVTJZemszTUdVMiJ9
    
  


volumes:
  postgres_data:
  


